// src/app/terms/page.tsx

import Link from "next/link";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div className={`ura-card p-6 md:p-7 ${className}`}>
      {children}
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return <div className="ura-section-label">{children}</div>;
}

function P({ children }: { children: React.ReactNode }) {
  return <div className="text-sm leading-relaxed ura-text-secondary">{children}</div>;
}

function Bullet({ children }: { children: React.ReactNode }) {
  return <li className="text-sm leading-relaxed ura-text-secondary">{children}</li>;
}

export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 py-8">
      <div className="mx-auto w-full max-w-3xl space-y-5">
        {/* Header */}
        <div className="mb-5">
          <div className="ura-section-label">URA</div>
          <div className="ura-page-title mt-1">Terms of Service</div>
          <div className="text-xs ura-text-muted mt-2">Effective Date: February 8, 2026</div>
        </div>

        <Card>
          <P>
            By accessing or using URA, you agree to these Terms of Service
            (&quot;Terms&quot;). If you do not agree, do not use the application.
          </P>
        </Card>

        <Card className="space-y-5">
          <div>
            <H2>Purpose of URA</H2>
            <div className="mt-2">
              <P>
                URA provides informational, symbolic, and reflective content designed
                to support personal orientation, self-reflection, and contextual
                awareness. URA does not provide medical, financial, legal, or
                psychological advice.
              </P>
            </div>
          </div>

          <div>
            <H2>No Professional Advice</H2>
            <div className="mt-2">
              <P>All content generated by URA is:</P>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <Bullet>Informational and interpretive</Bullet>
                <Bullet>Non-predictive</Bullet>
                <Bullet>Not a substitute for professional guidance</Bullet>
              </ul>
              <div className="mt-2">
                <P>
                  Users are solely responsible for how they interpret or act upon the
                  content provided.
                </P>
              </div>
            </div>
          </div>

          <div>
            <H2>User Accounts</H2>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <Bullet>
                Users are responsible for maintaining the security of their account.
              </Bullet>
              <Bullet>You agree to provide accurate information.</Bullet>
              <Bullet>
                We reserve the right to suspend or terminate accounts for misuse or
                violations.
              </Bullet>
            </ul>
          </div>

          <div>
            <H2>Acceptable Use</H2>
            <div className="mt-2">
              <P>You agree not to:</P>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <Bullet>Misuse or attempt to reverse-engineer the system</Bullet>
                <Bullet>Use URA for unlawful purposes</Bullet>
                <Bullet>Interfere with system operation or security</Bullet>
              </ul>
            </div>
          </div>

          <div>
            <H2>Intellectual Property</H2>
            <div className="mt-2">
              <P>
                All system design, text, synthesis logic, doctrine content, and
                outputs are the intellectual property of URA unless otherwise stated.
              </P>
              <div className="mt-2">
                <P>Users retain ownership of their original inputs.</P>
              </div>
            </div>
          </div>

          <div>
            <H2>Service Availability</H2>
            <div className="mt-2">
              <P>
                URA is provided &quot;as is&quot; and &quot;as available.&quot; We do
                not guarantee uninterrupted service or error-free operation.
              </P>
            </div>
          </div>

          <div>
            <H2>Limitation of Liability</H2>
            <div className="mt-2">
              <P>To the fullest extent permitted by law:</P>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <Bullet>
                  URA is not liable for decisions or outcomes based on its content
                </Bullet>
                <Bullet>
                  URA is not responsible for data loss, indirect damages, or
                  consequential harm
                </Bullet>
              </ul>
            </div>
          </div>

          <div>
            <H2>Termination</H2>
            <div className="mt-2">
              <P>
                Users may stop using URA at any time. We may terminate access for
                violations of these Terms.
              </P>
            </div>
          </div>

          <div>
            <H2>Changes to Terms</H2>
            <div className="mt-2">
              <P>
                We may update these Terms from time to time. Continued use
                constitutes acceptance.
              </P>
            </div>
          </div>

          <div>
            <H2>Governing Law</H2>
            <div className="mt-2">
              <P>
                These Terms are governed by the laws of the State of North Carolina,
                United States.
              </P>
            </div>
          </div>

          <div>
            <H2>Contact</H2>
            <div className="mt-2">
              <P>For questions regarding these Terms:</P>
              <div className="mt-1">
                <a
                  href="mailto:joshualharrington@gmail.com"
                  className="text-sm"
                  style={{ color: "var(--ura-accent-secondary)" }}
                >
                  joshualharrington@gmail.com
                </a>
              </div>
            </div>
          </div>
        </Card>

        <div className="text-center pb-8">
          <Link
            href="/about"
            className="text-xs"
            style={{ color: "var(--ura-text-muted)" }}
          >
            Back to About
          </Link>
        </div>
      </div>
    </div>
  );
}
