// src/app/privacy/page.tsx

import Link from "next/link";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div className={`ura-card p-6 md:p-7 ${className}`}>
      {children}
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return <div className="ura-section-label">{children}</div>;
}

function H3({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-xs font-medium uppercase tracking-wide ura-text-muted mt-3 mb-1">
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <div className="text-sm leading-relaxed ura-text-secondary">{children}</div>;
}

function Bullet({ children }: { children: React.ReactNode }) {
  return <li className="text-sm leading-relaxed ura-text-secondary">{children}</li>;
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen px-4 py-8">
      <div className="mx-auto w-full max-w-3xl space-y-5">
        {/* Header */}
        <div className="mb-5">
          <div className="ura-section-label">URA</div>
          <div className="ura-page-title mt-1">Privacy Policy</div>
          <div className="text-xs ura-text-muted mt-2">Last updated: February 8, 2026</div>
        </div>

        <Card>
          <P>
            URA (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) respects your
            privacy and is committed to protecting your personal data. This Privacy
            Policy explains how information is collected, used, stored, and disclosed
            when you use the URA application and related services.
          </P>
        </Card>

        <Card className="space-y-5">
          <div>
            <H2>Information We Collect</H2>
            <div className="mt-2">
              <P>We may collect the following types of information:</P>
            </div>

            <H3>Personal Information</H3>
            <ul className="list-disc pl-5 space-y-1">
              <Bullet>Account information (such as email address, username)</Bullet>
              <Bullet>
                Birth data provided by the user (date, time, and place of birth)
              </Bullet>
              <Bullet>
                User-generated inputs related to reflections, journaling, or settings
              </Bullet>
            </ul>

            <H3>Usage Data</H3>
            <ul className="list-disc pl-5 space-y-1">
              <Bullet>App interactions and feature usage</Bullet>
              <Bullet>Timestamps and session activity</Bullet>
              <Bullet>Device and basic technical information</Bullet>
            </ul>

            <H3>Derived &amp; Processed Data</H3>
            <ul className="list-disc pl-5 space-y-1">
              <Bullet>
                Symbolic or interpretive outputs generated from user inputs
              </Bullet>
              <Bullet>
                Cached readings or synthesized content generated by the system
              </Bullet>
            </ul>
          </div>

          <div>
            <H2>How We Use Information</H2>
            <div className="mt-2">
              <P>Information is used to:</P>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <Bullet>Provide core functionality of the URA application</Bullet>
                <Bullet>
                  Generate symbolic, interpretive, or reflective content
                </Bullet>
                <Bullet>Improve system performance and user experience</Bullet>
                <Bullet>Maintain account security and system integrity</Bullet>
              </ul>
              <div className="mt-2">
                <P>
                  URA does not use personal data for advertising or behavioral
                  tracking.
                </P>
              </div>
            </div>
          </div>

          <div>
            <H2>Automated Processing</H2>
            <div className="mt-2">
              <P>
                URA uses automated systems, including artificial intelligence models,
                to process user-provided information and generate interpretive or
                symbolic outputs. These outputs are informational in nature and are
                not professional advice.
              </P>
            </div>
          </div>

          <div>
            <H2>Data Storage &amp; Retention</H2>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <Bullet>
                Data is stored securely on our servers or trusted infrastructure
                providers.
              </Bullet>
              <Bullet>
                Personal data is retained only as long as necessary to provide the
                service.
              </Bullet>
              <Bullet>
                Users may request deletion of their account and associated data at
                any time.
              </Bullet>
            </ul>
          </div>

          <div>
            <H2>Data Sharing</H2>
            <div className="mt-2">
              <P>We do not sell personal data.</P>
              <div className="mt-2">
                <P>Data may be shared only with:</P>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                  <Bullet>
                    Infrastructure or service providers required to operate the app
                  </Bullet>
                  <Bullet>Legal authorities when required by law</Bullet>
                </ul>
              </div>
            </div>
          </div>

          <div>
            <H2>User Rights</H2>
            <div className="mt-2">
              <P>Users may:</P>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <Bullet>Access their personal data</Bullet>
                <Bullet>Request correction or deletion of their data</Bullet>
                <Bullet>Close their account at any time</Bullet>
              </ul>
              <div className="mt-2">
                <P>Requests can be made by contacting:</P>
                <div className="mt-1">
                  <a
                    href="mailto:joshualharrington@gmail.com"
                    className="text-sm"
                    style={{ color: "var(--ura-accent-secondary)" }}
                  >
                    joshualharrington@gmail.com
                  </a>
                </div>
              </div>
            </div>
          </div>

          <div>
            <H2>Security</H2>
            <div className="mt-2">
              <P>
                We take reasonable measures to protect user data against unauthorized
                access, loss, or misuse. However, no system is 100% secure.
              </P>
            </div>
          </div>

          <div>
            <H2>Children&apos;s Privacy</H2>
            <div className="mt-2">
              <P>
                URA is not intended for users under the age of 13. We do not
                knowingly collect data from children.
              </P>
            </div>
          </div>

          <div>
            <H2>Changes to This Policy</H2>
            <div className="mt-2">
              <P>
                This Privacy Policy may be updated periodically. Continued use of URA
                constitutes acceptance of the updated policy.
              </P>
            </div>
          </div>

          <div>
            <H2>Contact</H2>
            <div className="mt-2">
              <P>For questions about this policy, contact:</P>
              <div className="mt-1">
                <a
                  href="mailto:joshualharrington@gmail.com"
                  className="text-sm"
                  style={{ color: "var(--ura-accent-secondary)" }}
                >
                  joshualharrington@gmail.com
                </a>
              </div>
            </div>
          </div>
        </Card>

        <div className="text-center pb-8">
          <Link
            href="/about"
            className="text-xs"
            style={{ color: "var(--ura-text-muted)" }}
          >
            Back to About
          </Link>
        </div>
      </div>
    </div>
  );
}
