// src/lib/sabian/uraSabian.ts
// AUTO-GENERATED by scripts/generate-sabian.mjs
// Do not edit manually (regenerate instead).

export type UraSabianEntry = {
  idx: number;
  key: string;
  sign: string;
  degree: number;
  symbol: string;
  signal: string;
  shadow: string;
  directive: string;
  practice: string;
  journal: string;
  tags?: string[];
};

export const URA_SABIAN: UraSabianEntry[] = [
  // ... 360 entries
];
